# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Userscript Auto Releases

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup env
        run: |
          echo 'BUILD_PATH="../release"' > ./scripts/.env 
          echo 'VITE_BUILD_PATH="../../release"' > ./packages/core/.env
          echo 'VITE_BUILD_PATH="../../release"' > ./packages/scripts/.env
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DOWNLOAD_URL=https://github.com/ocsjs/ocsjs/releases/download/$VERSION/" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          npm install pnpm -g
          pnpm install -w
          cd packages/scripts
          pnpm install
          cd ../../
          npm run tsc
      - name: Build ocs scripts
        run: npm run build

      - name: Fetch Change logs
        if: runner.os == 'Linux'
        run: |
          echo "pwd: $(pwd)"
          echo "files:"
          ls -la
          echo "Displaying CHANGELOG_CURRENT.md content:"
          cat CHANGELOG_CURRENT.md
          if [ -f "CHANGELOG_CURRENT.md" ]; then
            CHANGE_LOGS=$(cat CHANGELOG_CURRENT.md)
            echo "CHANGE_LOGS<<EOF" >> $GITHUB_ENV
            echo "$CHANGE_LOGS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "CHANGELOG_CURRENT.md file not found"
          fi
        shell: bash
      - name: Generate release.txt
        if: runner.os == 'Linux'
        run: |
          if [ -z "$CHANGE_LOGS" ]; then
            echo "No change logs found, using default message"
            CHANGE_LOGS="More new features are now supported. Check for detailed changelog soon."
          else
            echo "Using found change logs"
          fi

          cat > release.txt << EOF
          $CHANGE_LOGS

          ## 资源下载列表

          - [用户脚本](${{ env.DOWNLOAD_URL }}ocs.user.js)
          - [用户脚本(全域名通用版)](${{ env.DOWNLOAD_URL }}ocs.common.user.js)
          - [核心库](${{ env.DOWNLOAD_URL }}core.js)
          - [简洁更新日志](${{ env.DOWNLOAD_URL }}CHANGELOG_SIMPLIFIED.md)

          ### 快捷访问
          - [官网](https://docs.ocsjs.com/)

          Created at ${{ env.BUILDTIME }}.
          EOF

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifactContentType: "html/text"
          artifacts: "./release/ocs.user.js,./release/ocs.common.user.js,./release/core.js,./release/index.js,./CHANGELOG_SIMPLIFIED.md"
          bodyFile: "./release.txt"
