name: Release Tag

on:
  pull_request:
    types: [closed]
    branches:
      - "4.0"

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  release-tag:
    # 只在 PR 被合并时执行
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          skip-github-pull-request: true # 只创建 Release，不创建 PR
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Trigger Build workflow
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN  }}
        run: |
          gh workflow run build-and-publish.yml --ref ${{ steps.release.outputs.tag_name }} --repo ${{ github.repository }}
